/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EquilibriumRouteImport } from './routes/equilibrium'
import { Route as EverydayRouteImport } from './routes/everyday'
import { Route as GeometryRouteImport } from './routes/geometry'
import { Route as HybridizationRouteImport } from './routes/hybridization'
import { Route as KineticsRouteImport } from './routes/kinetics'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EquilibriumRoute = EquilibriumRouteImport.update({
  id: '/equilibrium',
  path: '/equilibrium',
  getParentRoute: () => rootRouteImport,
} as any)
const EverydayRoute = EverydayRouteImport.update({
  id: '/everyday',
  path: '/everyday',
  getParentRoute: () => rootRouteImport,
} as any)
const GeometryRoute = GeometryRouteImport.update({
  id: '/geometry',
  path: '/geometry',
  getParentRoute: () => rootRouteImport,
} as any)
const HybridizationRoute = HybridizationRouteImport.update({
  id: '/hybridization',
  path: '/hybridization',
  getParentRoute: () => rootRouteImport,
} as any)
const KineticsRoute = KineticsRouteImport.update({
  id: '/kinetics',
  path: '/kinetics',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/equilibrium': typeof EquilibriumRoute
  '/everyday': typeof EverydayRoute
  '/geometry': typeof GeometryRoute
  '/hybridization': typeof HybridizationRoute
  '/kinetics': typeof KineticsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/equilibrium': typeof EquilibriumRoute
  '/everyday': typeof EverydayRoute
  '/geometry': typeof GeometryRoute
  '/hybridization': typeof HybridizationRoute
  '/kinetics': typeof KineticsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/equilibrium': typeof EquilibriumRoute
  '/everyday': typeof EverydayRoute
  '/geometry': typeof GeometryRoute
  '/hybridization': typeof HybridizationRoute
  '/kinetics': typeof KineticsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/equilibrium'
    | '/everyday'
    | '/geometry'
    | '/hybridization'
    | '/kinetics'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/equilibrium'
    | '/everyday'
    | '/geometry'
    | '/hybridization'
    | '/kinetics'
  id:
    | '__root__'
    | '/'
    | '/equilibrium'
    | '/everyday'
    | '/geometry'
    | '/hybridization'
    | '/kinetics'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EquilibriumRoute: typeof EquilibriumRoute
  EverydayRoute: typeof EverydayRoute
  GeometryRoute: typeof GeometryRoute
  HybridizationRoute: typeof HybridizationRoute
  KineticsRoute: typeof KineticsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equilibrium': {
      id: '/equilibrium'
      path: '/equilibrium'
      fullPath: '/equilibrium'
      preLoaderRoute: typeof EquilibriumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/everyday': {
      id: '/everyday'
      path: '/everyday'
      fullPath: '/everyday'
      preLoaderRoute: typeof EverydayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/geometry': {
      id: '/geometry'
      path: '/geometry'
      fullPath: '/geometry'
      preLoaderRoute: typeof GeometryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hybridization': {
      id: '/hybridization'
      path: '/hybridization'
      fullPath: '/hybridization'
      preLoaderRoute: typeof HybridizationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kinetics': {
      id: '/kinetics'
      path: '/kinetics'
      fullPath: '/kinetics'
      preLoaderRoute: typeof KineticsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EquilibriumRoute: EquilibriumRoute,
  EverydayRoute: EverydayRoute,
  GeometryRoute: GeometryRoute,
  HybridizationRoute: HybridizationRoute,
  KineticsRoute: KineticsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
