/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AcidBaseRouteImport } from './routes/acid-base'
import { Route as EverydayRouteImport } from './routes/everyday'
import { Route as KineticsRouteImport } from './routes/kinetics'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AcidBaseRoute = AcidBaseRouteImport.update({
  id: '/acid-base',
  path: '/acid-base',
  getParentRoute: () => rootRouteImport,
} as any)
const EverydayRoute = EverydayRouteImport.update({
  id: '/everyday',
  path: '/everyday',
  getParentRoute: () => rootRouteImport,
} as any)
const KineticsRoute = KineticsRouteImport.update({
  id: '/kinetics',
  path: '/kinetics',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/acid-base': typeof AcidBaseRoute
  '/everyday': typeof EverydayRoute
  '/kinetics': typeof KineticsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/acid-base': typeof AcidBaseRoute
  '/everyday': typeof EverydayRoute
  '/kinetics': typeof KineticsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/acid-base': typeof AcidBaseRoute
  '/everyday': typeof EverydayRoute
  '/kinetics': typeof KineticsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/acid-base' | '/everyday' | '/kinetics'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/acid-base' | '/everyday' | '/kinetics'
  id: '__root__' | '/' | '/acid-base' | '/everyday' | '/kinetics'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AcidBaseRoute: typeof AcidBaseRoute
  EverydayRoute: typeof EverydayRoute
  KineticsRoute: typeof KineticsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acid-base': {
      id: '/acid-base'
      path: '/acid-base'
      fullPath: '/acid-base'
      preLoaderRoute: typeof AcidBaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/everyday': {
      id: '/everyday'
      path: '/everyday'
      fullPath: '/everyday'
      preLoaderRoute: typeof EverydayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kinetics': {
      id: '/kinetics'
      path: '/kinetics'
      fullPath: '/kinetics'
      preLoaderRoute: typeof KineticsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AcidBaseRoute: AcidBaseRoute,
  EverydayRoute: EverydayRoute,
  KineticsRoute: KineticsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
